// 商品介绍直接取自物品定义，不为预览创建实体或触发初始化。
/proc/z121_rpg_item_description(obj/item/item_type)
	var/list/parts = list()
	var/description = initial(item_type.desc)
	if(length(description))
		parts += description
	// 弹药袋的初始介绍可能为空，按已核对的装填类型补充实际内装物品。
	if(ispath(item_type, /obj/item/quiver))
		var/static/list/quiver_ammo = list(
			/obj/item/quiver/arrows = /obj/item/ammo_casing/caseless/rogue/arrow/iron,
			/obj/item/quiver/bodkin = /obj/item/ammo_casing/caseless/rogue/arrow/steel,
			/obj/item/quiver/pyroarrows = /obj/item/ammo_casing/caseless/rogue/arrow/pyro,
			/obj/item/quiver/poisonarrows = /obj/item/ammo_casing/caseless/rogue/arrow/poison,
			/obj/item/quiver/bolts = /obj/item/ammo_casing/caseless/rogue/bolt,
			/obj/item/quiver/heavybluntbolts = /obj/item/ammo_casing/caseless/rogue/bolt/heavyblunt,
			/obj/item/quiver/pyrobolts = /obj/item/ammo_casing/caseless/rogue/bolt/pyro,
			/obj/item/quiver/javelin/iron = /obj/item/ammo_casing/caseless/rogue/javelin,
			/obj/item/quiver/javelin/steel = /obj/item/ammo_casing/caseless/rogue/javelin/steel,
			/obj/item/quiver/sling/iron = /obj/item/ammo_casing/caseless/rogue/sling_bullet/iron,
			/obj/item/quiver/sling/steel = /obj/item/ammo_casing/caseless/rogue/sling_bullet/steel,
			/obj/item/quiver/bullet/lead = /obj/item/ammo_casing/caseless/bullet/lead,
		)
		var/obj/item/quiver/quiver_type = item_type
		var/obj/item/ammo_type = quiver_ammo[item_type]
		if(ammo_type)
			parts += "内装[initial(quiver_type.max_storage)]枚[initial(ammo_type.name)]。[initial(ammo_type.desc)]"
		else if(item_type == /obj/item/quiver)
			parts += "用于收纳箭矢或弩矢的空箭袋，最多可装[initial(quiver_type.max_storage)]支。"
	// 成品药瓶往往只有通用容器介绍，额外展示原装药剂的名称、装量和介绍。
	if(ispath(item_type, /obj/item/reagent_containers/glass/bottle))
		var/obj/item/reagent_containers/glass/bottle/bottle_type = item_type
		var/list/reagents = initial(bottle_type.list_reagents)
		for(var/reagent_path in reagents)
			if(!ispath(reagent_path, /datum/reagent))
				continue
			var/datum/reagent/reagent_type = reagent_path
			parts += "内装[reagents[reagent_path]]单位[initial(reagent_type.name)]：[initial(reagent_type.description)]"
	return html_decode(GLOB.html_tags.Replace(jointext(parts, " "), ""))

// 套装按实际交付清单展示每种物品的数量与介绍，避免只描述第一件物品。
/proc/z121_rpg_catalog_description(list/entry)
	var/list/contents = entry["contents"]
	if(!length(contents))
		return z121_rpg_item_description(entry[2])
	var/list/item_counts = list()
	for(var/item_path in contents)
		item_counts[item_path] = 1 + item_counts[item_path]
	var/list/parts = list("整套包含：")
	for(var/item_path in item_counts)
		var/obj/item/item_type = item_path
		parts += "[initial(item_type.name)] ×[item_counts[item_path]]：[z121_rpg_item_description(item_type)]"
	return html_decode(GLOB.html_tags.Replace(jointext(parts, " "), ""))

// 金脸武器与护甲的静态副本：价格已按基础价四倍结算，不读取商店库存或供货包。
/proc/z121_rpg_expand_combat_catalog(list/base_catalog, tab)
	var/static/list/item_groups = list(
		// 原目录独有商品也归入对应类别；工具、照明和储物用品保留在其他类。
		/obj/item/rogueweapon/huntingknife = list(1, "铁制武器"),
		/obj/item/gun/ballistic/revolver/grenadelauncher/sling = list(4, "远程武器与弹药"),
		/obj/item/gun/ballistic/revolver/grenadelauncher/bow = list(4, "远程武器与弹药"),
		/obj/item/clothing/head/roguetown/roguehood = list(1, "轻型装备"),
		/obj/item/clothing/shoes/roguetown/boots = list(1, "轻型装备"),
		/obj/item/clothing/wrists/roguetown/bracers/leather = list(1, "轻型装备"),
		/obj/item/clothing/head/roguetown/helmet/leather = list(1, "轻型装备"),
		/obj/item/clothing/suit/roguetown/armor/leather/vest = list(1, "轻型装备"),
		/obj/item/clothing/suit/roguetown/armor/leather = list(1, "轻型装备"),
		/obj/item/clothing/suit/roguetown/armor/gambeson = list(1, "轻型装备"),
		/obj/item/clothing/neck/roguetown/coif = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet/heavy = list(4, "钢制装备"),
		/obj/item/rogueweapon/shield/iron = list(2, "铁制装备"),
		/obj/item/rogueweapon/sword/bronze = list(2, "青铜武器"),
		/obj/item/rogueweapon/katar/bronze = list(2, "青铜武器"),
		/obj/item/rogueweapon/sword/short/gladius = list(2, "青铜武器"),
		/obj/item/rogueweapon/sword/sabre/bronzekhopesh = list(2, "青铜武器"),
		/obj/item/rogueweapon/huntingknife/bronze = list(2, "青铜武器"),
		/obj/item/rogueweapon/huntingknife/combat/bronze = list(2, "青铜武器"),
		/obj/item/rogueweapon/sword/short/messer/bronze = list(2, "青铜武器"),
		/obj/item/rogueweapon/mace/bronze = list(2, "青铜武器"),
		/obj/item/rogueweapon/mace/warhammer/bronze = list(2, "青铜武器"),
		/obj/item/rogueweapon/spear/bronze = list(2, "青铜武器"),
		/obj/item/rogueweapon/spear/trident = list(2, "青铜武器"),
		/obj/item/rogueweapon/sword/falchion/militia/bronze = list(2, "青铜武器"),
		/obj/item/rogueweapon/sword/long/broadsword/bronze = list(2, "青铜武器"),
		/obj/item/rogueweapon/stoneaxe/woodcut/bronzebattleaxe = list(2, "青铜武器"),
		/obj/item/rogueweapon/stoneaxe/woodcut/bronze = list(2, "青铜武器"),
		/obj/item/rogueweapon/shield/bronze = list(2, "青铜武器"),
		/obj/item/rogueweapon/knuckles/bronzeknuckles = list(2, "青铜武器"),
		/obj/item/rogueweapon/whip/bronze = list(2, "青铜武器"),
		/obj/item/rogueweapon/whip/urumi/bronze = list(2, "青铜武器"),
		/obj/item/rogueweapon/shield/bronze/great = list(2, "青铜武器"),
		/obj/item/rogueweapon/huntingknife/idagger/steel/parrying/vaquero = list(5, "异国武器"),
		/obj/item/rogueweapon/sword/rapier/vaquero = list(5, "异国武器"),
		/obj/item/rogueweapon/sword/sabre/shamshir = list(5, "异国武器"),
		/obj/item/rogueweapon/stoneaxe/woodcut/steel/atgervi = list(5, "异国武器"),
		/obj/item/rogueweapon/woodstaff/naledi = list(5, "异国武器"),
		/obj/item/rogueweapon/stoneaxe/woodcut/pick = list(5, "异国武器"),
		/obj/item/rogueweapon/huntingknife/idagger/navaja = list(5, "异国武器"),
		/obj/item/rogueweapon/spear/naginata = list(5, "异国武器"),
		/obj/item/rogueweapon/mace/goden/kanabo = list(5, "异国武器"),
		/obj/item/rogueweapon/sword/long/kriegmesser/ssangsudo = list(5, "异国武器"),
		/obj/item/rogueweapon/sword/sabre/mulyeog = list(5, "异国武器"),
		/obj/item/rogueweapon/sword/short/kazengun = list(5, "异国武器"),
		/obj/item/rogueweapon/huntingknife/idagger/steel/kazengun = list(5, "异国武器"),
		/obj/item/rogueweapon/sword/sabre/hook = list(5, "异国武器"),
		/obj/item/rogueweapon/scabbard/sword/kazengun = list(5, "异国武器"),
		/obj/item/rogueweapon/scabbard/sword/kazengun/noparry/loadout = list(5, "异国武器"),
		/obj/item/rogueweapon/scabbard/sheath/kazengun = list(5, "异国武器"),
		/obj/item/rogueweapon/whip/nagaika = list(5, "异国武器"),
		/obj/item/rogueweapon/halberd/glaive = list(3, "钢制武器"),
		/obj/item/rogueweapon/sword/long/etruscan = list(5, "异国武器"),
		/obj/item/rogueweapon/handclaw = list(5, "异国武器"),
		/obj/item/rogueweapon/handclaw/steel = list(5, "异国武器"),
		/obj/item/rogueweapon/woodstaff/emerald/blacksteelstaff = list(5, "异国武器"),
		/obj/item/rogueweapon/sword/iron = list(1, "铁制武器"),
		/obj/item/rogueweapon/sword/short/iron = list(1, "铁制武器"),
		/obj/item/rogueweapon/sword/short/messer/iron = list(1, "铁制武器"),
		/obj/item/rogueweapon/sword/long/broadsword = list(1, "铁制武器"),
		/obj/item/rogueweapon/mace = list(1, "铁制武器"),
		/obj/item/rogueweapon/mace/cudgel = list(1, "铁制武器"),
		/obj/item/rogueweapon/huntingknife/idagger = list(1, "铁制武器"),
		/obj/item/rogueweapon/stoneaxe/woodcut = list(1, "铁制武器"),
		/obj/item/rogueweapon/woodstaff/quarterstaff/iron = list(1, "铁制武器"),
		/obj/item/rogueweapon/spear = list(1, "铁制武器"),
		/obj/item/rogueweapon/flail = list(1, "铁制武器"),
		/obj/item/rogueweapon/flail/peasantwarflail = list(1, "铁制武器"),
		/obj/item/rogueweapon/mace/warhammer = list(1, "铁制武器"),
		/obj/item/rogueweapon/greatsword/zwei = list(1, "铁制武器"),
		/obj/item/rogueweapon/greataxe = list(1, "铁制武器"),
		/obj/item/rogueweapon/halberd/bardiche = list(1, "铁制武器"),
		/obj/item/rogueweapon/eaglebeak/lucerne = list(1, "铁制武器"),
		/obj/item/rogueweapon/mace/goden = list(1, "铁制武器"),
		/obj/item/rogueweapon/whip = list(1, "铁制武器"),
		/obj/item/rogueweapon/shield/wood = list(1, "铁制武器"),
		/obj/item/rogueweapon/shield/tower = list(1, "铁制武器"),
		/obj/item/rogueweapon/shield/buckler = list(1, "铁制武器"),
		/obj/item/rogueweapon/shield/tower/metal = list(1, "铁制武器"),
		/obj/item/rogueweapon/huntingknife/idagger/steel = list(3, "钢制武器"),
		/obj/item/rogueweapon/katar = list(3, "钢制武器"),
		/obj/item/rogueweapon/knuckles = list(3, "钢制武器"),
		/obj/item/rogueweapon/sword/rapier = list(3, "钢制武器"),
		/obj/item/rogueweapon/sword/cutlass = list(3, "钢制武器"),
		/obj/item/rogueweapon/sword/short = list(3, "钢制武器"),
		/obj/item/rogueweapon/sword/short/falchion = list(3, "钢制武器"),
		/obj/item/rogueweapon/sword/short/messer = list(3, "钢制武器"),
		/obj/item/rogueweapon/sword/sabre = list(3, "钢制武器"),
		/obj/item/rogueweapon/flail/sflail = list(3, "钢制武器"),
		/obj/item/rogueweapon/mace/warhammer/steel = list(3, "钢制武器"),
		/obj/item/rogueweapon/woodstaff/quarterstaff/steel = list(3, "钢制武器"),
		/obj/item/rogueweapon/sword/long = list(3, "钢制武器"),
		/obj/item/rogueweapon/sword/long/broadsword/steel = list(3, "钢制武器"),
		/obj/item/rogueweapon/sword/long/kriegmesser = list(3, "钢制武器"),
		/obj/item/rogueweapon/stoneaxe/battle = list(3, "钢制武器"),
		/obj/item/rogueweapon/mace/steel = list(3, "钢制武器"),
		/obj/item/rogueweapon/greatsword = list(3, "钢制武器"),
		/obj/item/rogueweapon/greatsword/grenz = list(3, "钢制武器"),
		/obj/item/rogueweapon/greatsword/grenz/flamberge = list(3, "钢制武器"),
		/obj/item/rogueweapon/estoc = list(3, "钢制武器"),
		/obj/item/rogueweapon/greataxe/steel = list(3, "钢制武器"),
		/obj/item/rogueweapon/greataxe/steel/doublehead = list(3, "钢制武器"),
		/obj/item/rogueweapon/spear/billhook = list(3, "钢制武器"),
		/obj/item/rogueweapon/halberd = list(3, "钢制武器"),
		/obj/item/rogueweapon/eaglebeak = list(3, "钢制武器"),
		/obj/item/rogueweapon/mace/goden/steel = list(3, "钢制武器"),
		/obj/item/rogueweapon/flail/peasantwarflail/steel = list(3, "钢制武器"),
		/obj/item/rogueweapon/spear/partizan = list(3, "钢制武器"),
		/obj/item/rogueweapon/spear/boar = list(3, "钢制武器"),
		/obj/item/rogueweapon/spear/lance = list(3, "钢制武器"),
		/obj/item/rogueweapon/fishspear = list(3, "钢制武器"),
		/obj/item/rogueweapon/sword/long/rhomphaia = list(3, "钢制武器"),
		/obj/item/rogueweapon/sword/falx = list(3, "钢制武器"),
		/obj/item/storage/belt/rogue/leather/knifebelt/black/iron = list(4, "远程武器与弹药"),
		/obj/item/storage/belt/rogue/leather/knifebelt/black/steel = list(4, "远程武器与弹药"),
		/obj/item/quiver/javelin/iron = list(4, "远程武器与弹药"),
		/obj/item/quiver/javelin/steel = list(4, "远程武器与弹药"),
		/obj/item/rogueweapon/stoneaxe/hurlbat = list(4, "远程武器与弹药"),
		/obj/item/gun/ballistic/revolver/grenadelauncher/crossbow = list(4, "远程武器与弹药"),
		/obj/item/gun/ballistic/revolver/grenadelauncher/bow/recurve = list(4, "远程武器与弹药"),
		/obj/item/gun/ballistic/revolver/grenadelauncher/bow/longbow = list(4, "远程武器与弹药"),
		/obj/item/quiver = list(4, "远程武器与弹药"),
		/obj/item/quiver/arrows = list(4, "远程武器与弹药"),
		/obj/item/quiver/bodkin = list(4, "远程武器与弹药"),
		/obj/item/quiver/pyroarrows = list(4, "远程武器与弹药"),
		/obj/item/quiver/poisonarrows = list(4, "远程武器与弹药"),
		/obj/item/quiver/bolts = list(4, "远程武器与弹药"),
		/obj/item/quiver/heavybluntbolts = list(4, "远程武器与弹药"),
		/obj/item/quiver/pyrobolts = list(4, "远程武器与弹药"),
		/obj/item/quiver/sling/iron = list(4, "远程武器与弹药"),
		/obj/item/quiver/sling/steel = list(4, "远程武器与弹药"),
		/obj/item/net = list(4, "远程武器与弹药"),
		/obj/item/clothing/suit/roguetown/armor/chainmail/bronze = list(3, "青铜装备"),
		/obj/item/clothing/suit/roguetown/armor/chainmail/hauberk/bronze = list(3, "青铜装备"),
		/obj/item/clothing/neck/roguetown/chaincoif/bronze = list(3, "青铜装备"),
		/obj/item/clothing/neck/roguetown/gorget/bronze = list(3, "青铜装备"),
		/obj/item/clothing/neck/roguetown/bevor/bronze = list(3, "青铜装备"),
		/obj/item/clothing/suit/roguetown/armor/plate/bronze/light = list(3, "青铜装备"),
		/obj/item/clothing/suit/roguetown/armor/plate/bronze = list(3, "青铜装备"),
		/obj/item/clothing/suit/roguetown/armor/plate/scale/bronze = list(3, "青铜装备"),
		/obj/item/clothing/suit/roguetown/armor/plate/full/bronze/alt = list(3, "青铜装备"),
		/obj/item/clothing/suit/roguetown/armor/plate/full/bronze = list(3, "青铜装备"),
		/obj/item/clothing/wrists/roguetown/bracers/bronze = list(3, "青铜装备"),
		/obj/item/clothing/wrists/roguetown/bracers/chain/bronze = list(3, "青铜装备"),
		/obj/item/clothing/gloves/roguetown/chain/bronze = list(3, "青铜装备"),
		/obj/item/clothing/under/roguetown/chainlegs/kilt/bronze = list(3, "青铜装备"),
		/obj/item/clothing/under/roguetown/heavy_leather_pants/bronzeskirt = list(3, "青铜装备"),
		/obj/item/clothing/mask/rogue/facemask/bronze = list(3, "青铜装备"),
		/obj/item/clothing/mask/rogue/facemask/bronze/classic = list(3, "青铜装备"),
		/obj/item/clothing/shoes/roguetown/boots/armor/bronze = list(3, "青铜装备"),
		/obj/item/clothing/head/roguetown/helmet/heavy/bronze = list(3, "青铜装备"),
		/obj/item/clothing/head/roguetown/helmet/bronzegladiator = list(3, "青铜装备"),
		/obj/item/clothing/head/roguetown/helmet/bronze = list(3, "青铜装备"),
		/obj/item/clothing/suit/roguetown/armor/chainmail/iron = list(2, "铁制装备"),
		/obj/item/clothing/suit/roguetown/armor/chainmail/hauberk/iron = list(2, "铁制装备"),
		/obj/item/clothing/neck/roguetown/chaincoif/iron = list(2, "铁制装备"),
		/obj/item/clothing/neck/roguetown/gorget = list(2, "铁制装备"),
		/obj/item/clothing/neck/roguetown/bevor/iron = list(2, "铁制装备"),
		/obj/item/clothing/suit/roguetown/armor/plate/half/iron = list(2, "铁制装备"),
		/obj/item/clothing/suit/roguetown/armor/plate/full/iron = list(2, "铁制装备"),
		/obj/item/clothing/wrists/roguetown/splintarms/iron = list(2, "铁制装备"),
		/obj/item/clothing/wrists/roguetown/bracers/iron = list(2, "铁制装备"),
		/obj/item/clothing/gloves/roguetown/chain/iron = list(2, "铁制装备"),
		/obj/item/clothing/under/roguetown/chainlegs/iron = list(2, "铁制装备"),
		/obj/item/clothing/under/roguetown/splintlegs/iron = list(2, "铁制装备"),
		/obj/item/clothing/under/roguetown/platelegs/iron = list(2, "铁制装备"),
		/obj/item/clothing/under/roguetown/chainlegs/iron/kilt = list(2, "铁制装备"),
		/obj/item/clothing/mask/rogue/facemask = list(2, "铁制装备"),
		/obj/item/clothing/mask/rogue/wildguard = list(2, "铁制装备"),
		/obj/item/clothing/shoes/roguetown/boots/armor/iron = list(2, "铁制装备"),
		/obj/item/clothing/shoes/roguetown/boots/maille/iron = list(2, "铁制装备"),
		/obj/item/clothing/head/roguetown/helmet/skullcap = list(2, "铁制装备"),
		/obj/item/clothing/head/roguetown/helmet/horned = list(2, "铁制装备"),
		/obj/item/clothing/head/roguetown/helmet/kettle/iron = list(2, "铁制装备"),
		/obj/item/clothing/head/roguetown/helmet/sallet/iron = list(2, "铁制装备"),
		/obj/item/clothing/head/roguetown/helmet/sallet/visored/iron = list(2, "铁制装备"),
		/obj/item/clothing/head/roguetown/helmet/heavy/knight/iron = list(2, "铁制装备"),
		/obj/item/clothing/suit/roguetown/armor/gambeson/heavy = list(1, "轻型装备"),
		/obj/item/clothing/neck/roguetown/leather = list(1, "轻型装备"),
		/obj/item/clothing/wrists/roguetown/bracers/leather/heavy = list(1, "轻型装备"),
		/obj/item/clothing/under/roguetown/heavy_leather_pants = list(1, "轻型装备"),
		/obj/item/clothing/suit/roguetown/armor/leather/hide = list(1, "轻型装备"),
		/obj/item/clothing/suit/roguetown/armor/leather/heavy = list(1, "轻型装备"),
		/obj/item/clothing/suit/roguetown/armor/leather/studded = list(1, "轻型装备"),
		/obj/item/clothing/suit/roguetown/armor/leather/heavy/coat = list(1, "轻型装备"),
		/obj/item/clothing/suit/roguetown/armor/leather/heavy/jacket = list(1, "轻型装备"),
		/obj/item/clothing/gloves/roguetown/angle = list(1, "轻型装备"),
		/obj/item/clothing/neck/roguetown/coif/heavypadding = list(1, "轻型装备"),
		/obj/item/clothing/head/roguetown/roguehood/reinforced = list(1, "轻型装备"),
		/obj/item/clothing/head/roguetown/helmet/leather/armorhood = list(1, "轻型装备"),
		/obj/item/clothing/head/roguetown/helmet/leather/armorhood/advanced = list(1, "轻型装备"),
		/obj/item/clothing/suit/roguetown/armor/chainmail = list(4, "钢制装备"),
		/obj/item/clothing/suit/roguetown/armor/chainmail/hauberk = list(4, "钢制装备"),
		/obj/item/clothing/suit/roguetown/armor/plate = list(4, "钢制装备"),
		/obj/item/clothing/suit/roguetown/armor/plate/fluted = list(4, "钢制装备"),
		/obj/item/clothing/suit/roguetown/armor/plate/full = list(4, "钢制装备"),
		/obj/item/clothing/suit/roguetown/armor/plate/full/fluted = list(4, "钢制装备"),
		/obj/item/clothing/suit/roguetown/armor/brigandine/coatplates = list(4, "钢制装备"),
		/obj/item/clothing/suit/roguetown/armor/plate/half = list(4, "钢制装备"),
		/obj/item/clothing/suit/roguetown/armor/plate/scale = list(4, "钢制装备"),
		/obj/item/clothing/suit/roguetown/armor/brigandine = list(4, "钢制装备"),
		/obj/item/clothing/suit/roguetown/armor/brigandine/light = list(4, "钢制装备"),
		/obj/item/clothing/neck/roguetown/chaincoif = list(4, "钢制装备"),
		/obj/item/clothing/neck/roguetown/chaincoif/chainmantle = list(4, "钢制装备"),
		/obj/item/clothing/gloves/roguetown/chain = list(4, "钢制装备"),
		/obj/item/clothing/gloves/roguetown/plate = list(4, "钢制装备"),
		/obj/item/clothing/under/roguetown/splintlegs = list(4, "钢制装备"),
		/obj/item/clothing/under/roguetown/chainlegs = list(4, "钢制装备"),
		/obj/item/clothing/under/roguetown/platelegs = list(4, "钢制装备"),
		/obj/item/clothing/under/roguetown/chainlegs/kilt = list(4, "钢制装备"),
		/obj/item/clothing/wrists/roguetown/splintarms = list(4, "钢制装备"),
		/obj/item/clothing/wrists/roguetown/bracers/jackchain = list(4, "钢制装备"),
		/obj/item/clothing/wrists/roguetown/bracers = list(4, "钢制装备"),
		/obj/item/clothing/wrists/roguetown/bracers/chain = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet/winged = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet/kettle = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet/sallet = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet/sallet/visored = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet/heavy/bucket = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet/bascinet/pigface = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet/bascinet/pigface/hounskull = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet/heavy/volfplate = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet/bascinet = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet/bascinet/etruscan = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet/heavy/knight = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet/heavy/knight/armet = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet/heavy/guard = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet/heavy/sheriff = list(4, "钢制装备"),
		/obj/item/clothing/head/roguetown/helmet/heavy/beakhelm = list(4, "钢制装备"),
		/obj/item/clothing/neck/roguetown/bevor = list(4, "钢制装备"),
		/obj/item/clothing/neck/roguetown/gorget/steel = list(4, "钢制装备"),
		/obj/item/clothing/shoes/roguetown/boots/armor = list(4, "钢制装备"),
		/obj/item/clothing/shoes/roguetown/boots/maille = list(4, "钢制装备"),
		/obj/item/clothing/mask/rogue/facemask/steel = list(4, "钢制装备"),
		/obj/item/storage/belt/rogue/leather/steel = list(4, "钢制装备"),
		/obj/item/storage/belt/rogue/leather/steel/tasset = list(4, "钢制装备"),
		/obj/item/quiver/bullet/lead = list(4, "远程武器与弹药"),
	)
	var/static/list/additions = list(
		"青铜单手剑（120积分）" = list(120, /obj/item/rogueweapon/sword/bronze, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"青铜拳刃（120积分）" = list(120, /obj/item/rogueweapon/katar/bronze, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"短剑（120积分）" = list(120, /obj/item/rogueweapon/sword/short/gladius, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"寇派什弯刀（120积分）" = list(120, /obj/item/rogueweapon/sword/sabre/bronzekhopesh, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"青铜匕首（120积分）" = list(120, /obj/item/rogueweapon/huntingknife/bronze, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"西德阿姆（216积分）" = list(216, /obj/item/rogueweapon/huntingknife/combat/bronze, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"马凯拉短剑（120积分）" = list(120, /obj/item/rogueweapon/sword/short/messer/bronze, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"青铜钉头锤（120积分）" = list(120, /obj/item/rogueweapon/mace/bronze, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"青铜战棍（216积分）" = list(216, /obj/item/rogueweapon/mace/warhammer/bronze, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"青铜矛（240积分）" = list(240, /obj/item/rogueweapon/spear/bronze, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"科皮斯（216积分）" = list(216, /obj/item/rogueweapon/sword/falchion/militia/bronze, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"斯帕塔长剑（240积分）" = list(240, /obj/item/rogueweapon/sword/long/broadsword/bronze, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"青铜战斧（216积分）" = list(216, /obj/item/rogueweapon/stoneaxe/woodcut/bronzebattleaxe, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"青铜斧（120积分）" = list(120, /obj/item/rogueweapon/stoneaxe/woodcut/bronze, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"霍普隆盾（240积分）" = list(240, /obj/item/rogueweapon/shield/bronze, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"青铜指虎（120积分）" = list(120, /obj/item/rogueweapon/knuckles/bronzeknuckles, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"青铜鞭（168积分）" = list(168, /obj/item/rogueweapon/whip/bronze, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"青铜软剑（200积分）" = list(200, /obj/item/rogueweapon/whip/urumi/bronze, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"青铜标枪组（2支）（140积分）" = list(140, /obj/item/ammo_casing/caseless/rogue/javelin/bronze, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器", "contents" = list(/obj/item/ammo_casing/caseless/rogue/javelin/bronze, /obj/item/ammo_casing/caseless/rogue/javelin/bronze)),
		"霍普隆巨盾（320积分）" = list(320, /obj/item/rogueweapon/shield/bronze/great, "tab" = "weapon", "group_order" = 2, "group" = "青铜武器"),
		"船帆匕首（320积分）" = list(320, /obj/item/rogueweapon/huntingknife/idagger/steel/parrying/vaquero, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"杯护手刺剑（480积分）" = list(480, /obj/item/rogueweapon/sword/rapier/vaquero, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"沙姆希尔弯刀（560积分）" = list(560, /obj/item/rogueweapon/sword/sabre/shamshir, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"胡须战斧（320积分）" = list(320, /obj/item/rogueweapon/stoneaxe/woodcut/steel/atgervi, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"纳勒迪战杖（1200积分）" = list(1200, /obj/item/rogueweapon/woodstaff/naledi, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"普拉斯基斧（560积分）" = list(560, /obj/item/rogueweapon/stoneaxe/woodcut/pick, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"纳瓦哈折刀（320积分）" = list(320, /obj/item/rogueweapon/huntingknife/idagger/navaja, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"薙刀（560积分）" = list(560, /obj/item/rogueweapon/spear/naginata, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"铁包棒（800积分）" = list(800, /obj/item/rogueweapon/mace/goden/kanabo, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"双手刀（800积分）" = list(800, /obj/item/rogueweapon/sword/long/kriegmesser/ssangsudo, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"环刀（480积分）" = list(480, /obj/item/rogueweapon/sword/sabre/mulyeog, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"钢小太刀（480积分）" = list(480, /obj/item/rogueweapon/sword/short/kazengun, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"钢短刀（320积分）" = list(320, /obj/item/rogueweapon/huntingknife/idagger/steel/kazengun, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"钩剑（400积分）" = list(400, /obj/item/rogueweapon/sword/sabre/hook, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"简式风军剑鞘（320积分）" = list(320, /obj/item/rogueweapon/scabbard/sword/kazengun, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"仪式剑鞘（160积分）" = list(160, /obj/item/rogueweapon/scabbard/sword/kazengun/noparry/loadout, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"素漆刀套（80积分）" = list(80, /obj/item/rogueweapon/scabbard/sheath/kazengun, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"纳盖卡鞭（480积分）" = list(480, /obj/item/rogueweapon/whip/nagaika, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"偃月刀（420积分）" = list(420, /obj/item/rogueweapon/halberd/glaive, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"篮护长剑（5636积分）" = list(5636, /obj/item/rogueweapon/sword/long/etruscan, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"铁猎犬爪（600积分）" = list(600, /obj/item/rogueweapon/handclaw, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"钢螳螂爪（800积分）" = list(800, /obj/item/rogueweapon/handclaw/steel, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"黑钢法杖（600积分）" = list(600, /obj/item/rogueweapon/woodstaff/emerald/blacksteelstaff, "tab" = "weapon", "group_order" = 5, "group" = "异国武器"),
		"铁短剑（100积分）" = list(100, /obj/item/rogueweapon/sword/short/iron, "tab" = "weapon", "group_order" = 1, "group" = "铁制武器"),
		"猎剑（100积分）" = list(100, /obj/item/rogueweapon/sword/short/messer/iron, "tab" = "weapon", "group_order" = 1, "group" = "铁制武器"),
		"阔剑（160积分）" = list(160, /obj/item/rogueweapon/sword/long/broadsword, "tab" = "weapon", "group_order" = 1, "group" = "铁制武器"),
		"钉头锤（100积分）" = list(100, /obj/item/rogueweapon/mace, "tab" = "weapon", "group_order" = 1, "group" = "铁制武器"),
		"铁匕首（100积分）" = list(100, /obj/item/rogueweapon/huntingknife/idagger, "tab" = "weapon", "group_order" = 1, "group" = "铁制武器"),
		"伐木斧（100积分）" = list(100, /obj/item/rogueweapon/stoneaxe/woodcut, "tab" = "weapon", "group_order" = 1, "group" = "铁制武器"),
		"铁头长杖（100积分）" = list(100, /obj/item/rogueweapon/woodstaff/quarterstaff/iron, "tab" = "weapon", "group_order" = 1, "group" = "铁制武器"),
		"民兵长连枷（180积分）" = list(180, /obj/item/rogueweapon/flail/peasantwarflail, "tab" = "weapon", "group_order" = 1, "group" = "铁制武器"),
		"战锤（100积分）" = list(100, /obj/item/rogueweapon/mace/warhammer, "tab" = "weapon", "group_order" = 1, "group" = "铁制武器"),
		"克莱摩大剑（160积分）" = list(160, /obj/item/rogueweapon/greatsword/zwei, "tab" = "weapon", "group_order" = 1, "group" = "铁制武器"),
		"巨斧（180积分）" = list(180, /obj/item/rogueweapon/greataxe, "tab" = "weapon", "group_order" = 1, "group" = "铁制武器"),
		"长柄战斧（180积分）" = list(180, /obj/item/rogueweapon/halberd/bardiche, "tab" = "weapon", "group_order" = 1, "group" = "铁制武器"),
		"卢塞恩锤（180积分）" = list(180, /obj/item/rogueweapon/eaglebeak/lucerne, "tab" = "weapon", "group_order" = 1, "group" = "铁制武器"),
		"小圆盾（280积分）" = list(280, /obj/item/rogueweapon/shield/buckler, "tab" = "weapon", "group_order" = 1, "group" = "铁制武器"),
		"鸢盾（280积分）" = list(280, /obj/item/rogueweapon/shield/tower/metal, "tab" = "weapon", "group_order" = 1, "group" = "铁制武器"),
		"钢匕首（160积分）" = list(160, /obj/item/rogueweapon/huntingknife/idagger/steel, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"拳刃（160积分）" = list(160, /obj/item/rogueweapon/katar, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"钢指虎（160积分）" = list(160, /obj/item/rogueweapon/knuckles, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"刺剑（160积分）" = list(160, /obj/item/rogueweapon/sword/rapier, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"短弯刀（160积分）" = list(160, /obj/item/rogueweapon/sword/cutlass, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"法刀（160积分）" = list(160, /obj/item/rogueweapon/sword/short/falchion, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"钢猎剑（160积分）" = list(160, /obj/item/rogueweapon/sword/short/messer, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"军刀（160积分）" = list(160, /obj/item/rogueweapon/sword/sabre, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"钢连枷（160积分）" = list(160, /obj/item/rogueweapon/flail/sflail, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"钢战锤（160积分）" = list(160, /obj/item/rogueweapon/mace/warhammer/steel, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"钢头长杖（160积分）" = list(160, /obj/item/rogueweapon/woodstaff/quarterstaff/steel, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"钢制阔剑（280积分）" = list(280, /obj/item/rogueweapon/sword/long/broadsword/steel, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"双手大刀（280积分）" = list(280, /obj/item/rogueweapon/sword/long/kriegmesser, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"钢制双手剑（420积分）" = list(420, /obj/item/rogueweapon/greatsword/grenz, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"钢制焰形剑（420积分）" = list(420, /obj/item/rogueweapon/greatsword/grenz/flamberge, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"钢巨斧（300积分）" = list(300, /obj/item/rogueweapon/greataxe/steel, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"双头钢巨斧（440积分）" = list(440, /obj/item/rogueweapon/greataxe/steel/doublehead, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"钩镰枪（160积分）" = list(160, /obj/item/rogueweapon/spear/billhook, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"鹰喙锤（300积分）" = list(300, /obj/item/rogueweapon/eaglebeak, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"巨型钉头锤（300积分）" = list(300, /obj/item/rogueweapon/mace/goden/steel, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"巨型连枷（320积分）" = list(320, /obj/item/rogueweapon/flail/peasantwarflail/steel, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"帕提赞长戟（320积分）" = list(320, /obj/item/rogueweapon/spear/partizan, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"猎猪矛（320积分）" = list(320, /obj/item/rogueweapon/spear/boar, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"骑枪（320积分）" = list(320, /obj/item/rogueweapon/spear/lance, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"渔叉（300积分）" = list(300, /obj/item/rogueweapon/fishspear, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"罗姆法亚弯剑（280积分）" = list(280, /obj/item/rogueweapon/sword/long/rhomphaia, "tab" = "weapon", "group_order" = 3, "group" = "钢制武器"),
		"铁飞刃腰带（100积分）" = list(100, /obj/item/storage/belt/rogue/leather/knifebelt/black/iron, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"钢飞刃腰带（180积分）" = list(180, /obj/item/storage/belt/rogue/leather/knifebelt/black/steel, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"铁标枪袋（4支）（160积分）" = list(160, /obj/item/quiver/javelin/iron, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"钢标枪袋（4支）（320积分）" = list(320, /obj/item/quiver/javelin/steel, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"投掷斧（200积分）" = list(200, /obj/item/rogueweapon/stoneaxe/hurlbat, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"反曲弓（80积分）" = list(80, /obj/item/gun/ballistic/revolver/grenadelauncher/bow/recurve, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"紫杉长弓（180积分）" = list(180, /obj/item/gun/ballistic/revolver/grenadelauncher/bow/longbow, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"空箭袋（20积分）" = list(20, /obj/item/quiver, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"铁阔头箭袋（20支）（140积分）" = list(140, /obj/item/quiver/arrows, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"钢锥头箭袋（20支）（400积分）" = list(400, /obj/item/quiver/bodkin, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"燃烧箭袋（20支）（400积分）" = list(400, /obj/item/quiver/pyroarrows, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"毒箭袋（20支）（400积分）" = list(400, /obj/item/quiver/poisonarrows, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"弩矢袋（20支）（140积分）" = list(140, /obj/item/quiver/bolts, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"重型钝头弩矢袋（20支）（140积分）" = list(140, /obj/item/quiver/heavybluntbolts, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"燃烧弩矢袋（20支）（400积分）" = list(400, /obj/item/quiver/pyrobolts, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"瓶装炸弹组（5枚）（160积分）" = list(160, /obj/item/bomb, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药", "contents" = list(/obj/item/bomb, /obj/item/bomb, /obj/item/bomb, /obj/item/bomb, /obj/item/bomb)),
		"投石索与弹袋套装（60积分）" = list(60, /obj/item/gun/ballistic/revolver/grenadelauncher/sling, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药", "contents" = list(/obj/item/gun/ballistic/revolver/grenadelauncher/sling, /obj/item/quiver/sling)),
		"铁制投石索弹袋（20枚）（140积分）" = list(140, /obj/item/quiver/sling/iron, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"钢制投石索弹袋（20枚）（320积分）" = list(320, /obj/item/quiver/sling/steel, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"捕网（80积分）" = list(80, /obj/item/net, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
		"青铜锁子短甲（100积分）" = list(100, /obj/item/clothing/suit/roguetown/armor/chainmail/bronze, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜锁子甲（160积分）" = list(160, /obj/item/clothing/suit/roguetown/armor/chainmail/hauberk/bronze, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜锁链护头巾（100积分）" = list(100, /obj/item/clothing/neck/roguetown/chaincoif/bronze, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜护颈（100积分）" = list(100, /obj/item/clothing/neck/roguetown/gorget/bronze, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜护喉甲（100积分）" = list(100, /obj/item/clothing/neck/roguetown/bevor/bronze, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜护心甲（140积分）" = list(140, /obj/item/clothing/suit/roguetown/armor/plate/bronze/light, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜胸甲（140积分）" = list(140, /obj/item/clothing/suit/roguetown/armor/plate/bronze, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜鳞甲（200积分）" = list(200, /obj/item/clothing/suit/roguetown/armor/plate/scale/bronze, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜全装甲组件（720积分）" = list(720, /obj/item/clothing/suit/roguetown/armor/plate/full/bronze/alt, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜全装板甲（880积分）" = list(880, /obj/item/clothing/suit/roguetown/armor/plate/full/bronze, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜护腕（100积分）" = list(100, /obj/item/clothing/wrists/roguetown/bracers/bronze, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜锁链袖套（80积分）" = list(80, /obj/item/clothing/wrists/roguetown/bracers/chain/bronze, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜锁甲护手（80积分）" = list(80, /obj/item/clothing/gloves/roguetown/chain/bronze, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜锁甲裙铠（100积分）" = list(100, /obj/item/clothing/under/roguetown/chainlegs/kilt/bronze, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜锁甲裙（140积分）" = list(140, /obj/item/clothing/under/roguetown/heavy_leather_pants/bronzeskirt, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜面具（100积分）" = list(100, /obj/item/clothing/mask/rogue/facemask/bronze, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜死亡面具（100积分）" = list(100, /obj/item/clothing/mask/rogue/facemask/bronze/classic, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜胫甲（100积分）" = list(100, /obj/item/clothing/shoes/roguetown/boots/armor/bronze, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜巴布塔盔（200积分）" = list(200, /obj/item/clothing/head/roguetown/helmet/heavy/bronze, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜穆尔米洛盔（100积分）" = list(100, /obj/item/clothing/head/roguetown/helmet/bronzegladiator, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"青铜伊利里亚头盔（100积分）" = list(100, /obj/item/clothing/head/roguetown/helmet/bronze, "tab" = "equipment", "group_order" = 3, "group" = "青铜装备"),
		"掠夺者皮甲套装（500积分）" = list(500, /obj/item/clothing/head/roguetown/helmet/bascinet/atgervi/gronn, "tab" = "equipment", "group_order" = 5, "group" = "异域装备", "contents" = list(/obj/item/clothing/head/roguetown/helmet/bascinet/atgervi/gronn, /obj/item/clothing/suit/roguetown/armor/leather/heavy/gronn, /obj/item/clothing/under/roguetown/trou/leather/gronn, /obj/item/clothing/gloves/roguetown/angle/gronn)),
		"拜林锁甲套装（900积分）" = list(900, /obj/item/clothing/head/roguetown/helmet/bascinet/atgervi/gronn/ownel, "tab" = "equipment", "group_order" = 5, "group" = "异域装备", "contents" = list(/obj/item/clothing/head/roguetown/helmet/bascinet/atgervi/gronn/ownel, /obj/item/clothing/suit/roguetown/armor/brigandine/gronn, /obj/item/clothing/gloves/roguetown/chain/gronn, /obj/item/clothing/under/roguetown/splintlegs/iron/gronn)),
		"怯薛板甲套装（1600积分）" = list(1600, /obj/item/clothing/head/roguetown/helmet/heavy/bucket/gronn, "tab" = "equipment", "group_order" = 5, "group" = "异域装备", "contents" = list(/obj/item/clothing/head/roguetown/helmet/heavy/bucket/gronn, /obj/item/clothing/suit/roguetown/armor/plate/iron/gronn, /obj/item/clothing/gloves/roguetown/plate/iron/gronn, /obj/item/clothing/under/roguetown/platelegs/iron/gronn, /obj/item/clothing/shoes/roguetown/boots/armor/iron/gronn)),
		"铁制锁子短甲（100积分）" = list(100, /obj/item/clothing/suit/roguetown/armor/chainmail/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁制锁子甲（160积分）" = list(160, /obj/item/clothing/suit/roguetown/armor/chainmail/hauberk/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁锁链护头巾（100积分）" = list(100, /obj/item/clothing/neck/roguetown/chaincoif/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"护喉（100积分）" = list(100, /obj/item/clothing/neck/roguetown/gorget, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁护颚（100积分）" = list(100, /obj/item/clothing/neck/roguetown/bevor/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁胸甲（140积分）" = list(140, /obj/item/clothing/suit/roguetown/armor/plate/half/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁制板甲（880积分）" = list(880, /obj/item/clothing/suit/roguetown/armor/plate/full/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"拼铁臂甲（120积分）" = list(120, /obj/item/clothing/wrists/roguetown/splintarms/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁臂甲（100积分）" = list(100, /obj/item/clothing/wrists/roguetown/bracers/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁制锁甲护手（80积分）" = list(80, /obj/item/clothing/gloves/roguetown/chain/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁制锁甲腿铠（100积分）" = list(100, /obj/item/clothing/under/roguetown/chainlegs/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"拼铁护腿（140积分）" = list(140, /obj/item/clothing/under/roguetown/splintlegs/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁制板甲腿铠（160积分）" = list(160, /obj/item/clothing/under/roguetown/platelegs/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁制锁甲裙铠（100积分）" = list(100, /obj/item/clothing/under/roguetown/chainlegs/iron/kilt, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁面具（100积分）" = list(100, /obj/item/clothing/mask/rogue/facemask, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"荒野守卫（100积分）" = list(100, /obj/item/clothing/mask/rogue/wildguard, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁板靴（100积分）" = list(100, /obj/item/clothing/shoes/roguetown/boots/armor/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁链甲靴（100积分）" = list(100, /obj/item/clothing/shoes/roguetown/boots/maille/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"骷髅帽（100积分）" = list(100, /obj/item/clothing/head/roguetown/helmet/skullcap, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"角饰帽（100积分）" = list(100, /obj/item/clothing/head/roguetown/helmet/horned, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁锅盔（100积分）" = list(100, /obj/item/clothing/head/roguetown/helmet/kettle/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁萨勒盔（100积分）" = list(100, /obj/item/clothing/head/roguetown/helmet/sallet/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁带面罩萨勒盔（160积分）" = list(160, /obj/item/clothing/head/roguetown/helmet/sallet/visored/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"铁骑士头盔（160积分）" = list(160, /obj/item/clothing/head/roguetown/helmet/heavy/knight/iron, "tab" = "equipment", "group_order" = 2, "group" = "铁制装备"),
		"加厚绗缝护甲衣（160积分）" = list(160, /obj/item/clothing/suit/roguetown/armor/gambeson/heavy, "tab" = "equipment", "group_order" = 1, "group" = "轻型装备"),
		"硬化皮革护喉（80积分）" = list(80, /obj/item/clothing/neck/roguetown/leather, "tab" = "equipment", "group_order" = 1, "group" = "轻型装备"),
		"硬化皮臂甲（80积分）" = list(80, /obj/item/clothing/wrists/roguetown/bracers/leather/heavy, "tab" = "equipment", "group_order" = 1, "group" = "轻型装备"),
		"硬化皮裤（120积分）" = list(120, /obj/item/clothing/under/roguetown/heavy_leather_pants, "tab" = "equipment", "group_order" = 1, "group" = "轻型装备"),
		"兽皮甲（120积分）" = list(120, /obj/item/clothing/suit/roguetown/armor/leather/hide, "tab" = "equipment", "group_order" = 1, "group" = "轻型装备"),
		"硬化皮甲（120积分）" = list(120, /obj/item/clothing/suit/roguetown/armor/leather/heavy, "tab" = "equipment", "group_order" = 1, "group" = "轻型装备"),
		"铆钉皮甲（160积分）" = list(160, /obj/item/clothing/suit/roguetown/armor/leather/studded, "tab" = "equipment", "group_order" = 1, "group" = "轻型装备"),
		"硬化皮大衣（140积分）" = list(140, /obj/item/clothing/suit/roguetown/armor/leather/heavy/coat, "tab" = "equipment", "group_order" = 1, "group" = "轻型装备"),
		"硬化皮夹克（140积分）" = list(140, /obj/item/clothing/suit/roguetown/armor/leather/heavy/jacket, "tab" = "equipment", "group_order" = 1, "group" = "轻型装备"),
		"重型皮手套（80积分）" = list(80, /obj/item/clothing/gloves/roguetown/angle, "tab" = "equipment", "group_order" = 1, "group" = "轻型装备"),
		"厚实衬垫护头巾（140积分）" = list(140, /obj/item/clothing/neck/roguetown/coif/heavypadding, "tab" = "equipment", "group_order" = 1, "group" = "轻型装备"),
		"加固兜帽（160积分）" = list(160, /obj/item/clothing/head/roguetown/roguehood/reinforced, "tab" = "equipment", "group_order" = 1, "group" = "轻型装备"),
		"衬垫皮革兜帽（160积分）" = list(160, /obj/item/clothing/head/roguetown/helmet/leather/armorhood, "tab" = "equipment", "group_order" = 1, "group" = "轻型装备"),
		"铆钉皮革兜帽（200积分）" = list(200, /obj/item/clothing/head/roguetown/helmet/leather/armorhood/advanced, "tab" = "equipment", "group_order" = 1, "group" = "轻型装备"),
		"锁子甲（360积分）" = list(360, /obj/item/clothing/suit/roguetown/armor/chainmail/hauberk, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"沟槽半身板甲（620积分）" = list(620, /obj/item/clothing/suit/roguetown/armor/plate/fluted, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"板甲（1400积分）" = list(1400, /obj/item/clothing/suit/roguetown/armor/plate/full, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"沟槽板甲（1520积分）" = list(1520, /obj/item/clothing/suit/roguetown/armor/plate/full/fluted, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"板片外衣（380积分）" = list(380, /obj/item/clothing/suit/roguetown/armor/brigandine/coatplates, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"钢胸甲（360积分）" = list(360, /obj/item/clothing/suit/roguetown/armor/plate/half, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"鳞甲（360积分）" = list(360, /obj/item/clothing/suit/roguetown/armor/plate/scale, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"轻型板甲衣（220积分）" = list(220, /obj/item/clothing/suit/roguetown/armor/brigandine/light, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"锁链护头巾（200积分）" = list(200, /obj/item/clothing/neck/roguetown/chaincoif, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"锁链披肩（200积分）" = list(200, /obj/item/clothing/neck/roguetown/chaincoif/chainmantle, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"板条腿铠（240积分）" = list(240, /obj/item/clothing/under/roguetown/splintlegs, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"钢制锁甲腿铠（200积分）" = list(200, /obj/item/clothing/under/roguetown/chainlegs, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"钢制板甲腿铠（360积分）" = list(360, /obj/item/clothing/under/roguetown/platelegs, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"钢制锁甲裙铠（200积分）" = list(200, /obj/item/clothing/under/roguetown/chainlegs/kilt, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"板条护臂（220积分）" = list(220, /obj/item/clothing/wrists/roguetown/splintarms, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"护臂链条（200积分）" = list(200, /obj/item/clothing/wrists/roguetown/bracers/jackchain, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"锁链袖套（200积分）" = list(200, /obj/item/clothing/wrists/roguetown/bracers/chain, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"翼饰帽（200积分）" = list(200, /obj/item/clothing/head/roguetown/helmet/winged, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"带面罩萨勒盔（360积分）" = list(360, /obj/item/clothing/head/roguetown/helmet/sallet/visored, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"桶盔（360积分）" = list(360, /obj/item/clothing/head/roguetown/helmet/heavy/bucket, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"猪面盆盔（360积分）" = list(360, /obj/item/clothing/head/roguetown/helmet/bascinet/pigface, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"犬首盆盔（360积分）" = list(360, /obj/item/clothing/head/roguetown/helmet/bascinet/pigface/hounskull, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"沃尔夫面甲头盔（360积分）" = list(360, /obj/item/clothing/head/roguetown/helmet/heavy/volfplate, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"伊特鲁斯卡盆盔（360积分）" = list(360, /obj/item/clothing/head/roguetown/helmet/bascinet/etruscan, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"骑士头盔（360积分）" = list(360, /obj/item/clothing/head/roguetown/helmet/heavy/knight, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"阿米特盔（360积分）" = list(360, /obj/item/clothing/head/roguetown/helmet/heavy/knight/armet, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"钢萨伏依盔（360积分）" = list(360, /obj/item/clothing/head/roguetown/helmet/heavy/guard, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"栅栏头盔（360积分）" = list(360, /obj/item/clothing/head/roguetown/helmet/heavy/sheriff, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"鸟喙头盔（360积分）" = list(360, /obj/item/clothing/head/roguetown/helmet/heavy/beakhelm, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"护颚（200积分）" = list(200, /obj/item/clothing/neck/roguetown/bevor, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"钢护喉（200积分）" = list(200, /obj/item/clothing/neck/roguetown/gorget/steel, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"板甲靴（200积分）" = list(200, /obj/item/clothing/shoes/roguetown/boots/armor, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"链甲靴（200积分）" = list(200, /obj/item/clothing/shoes/roguetown/boots/maille, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"钢面具（200积分）" = list(200, /obj/item/clothing/mask/rogue/facemask/steel, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"钢腰带（200积分）" = list(200, /obj/item/storage/belt/rogue/leather/steel, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"腿甲腰带（200积分）" = list(200, /obj/item/storage/belt/rogue/leather/steel/tasset, "tab" = "equipment", "group_order" = 4, "group" = "钢制装备"),
		"铅弹袋（8枚）（320积分）" = list(320, /obj/item/quiver/bullet/lead, "tab" = "weapon", "group_order" = 4, "group" = "远程武器与弹药"),
	)
	for(var/display in base_catalog)
		var/list/entry = base_catalog[display]
		var/list/group = item_groups[entry[2]]
		entry["group_order"] = group ? group[1] : 6
		entry["group"] = group ? group[2] : (tab == "weapon" ? "其他武器" : "其他装备")
		if(entry[2] == /obj/item/rogueweapon/shield/wood)
			entry["group_order"] = 1
			entry["group"] = "轻型装备"
			continue
		// 原有盾牌留在装备页，按对应材质归类。
		if(tab == "equipment" && group && findtext(group[2], "武器"))
			entry["group"] = replacetext(group[2], "武器", "装备")
			entry["group_order"] = group[1] == 1 ? 2 : (group[1] == 2 ? 3 : 4)
	for(var/display in additions)
		var/list/entry = additions[display]
		if(entry["tab"] != tab)
			continue
		var/key = display
		while(key in base_catalog)
			key += "·补充"
		base_catalog[key] = entry.Copy()
	return base_catalog

// 生食使用已有成品类型，价格为最终单价，不叠加其他分类倍率。
/proc/z121_rpg_raw_food_catalog()
	return z121_rpg_price_catalog(list(
		"禽肉" = list(15, /obj/item/reagent_containers/food/snacks/rogue/meat/poultry/cutlet, "group_order" = 1, "group" = "生肉"),
		"生肉排" = list(20, /obj/item/reagent_containers/food/snacks/rogue/meat/steak, "group_order" = 1, "group" = "生肉"),
		"生猪肉" = list(25, /obj/item/reagent_containers/food/snacks/rogue/meat/fatty, "group_order" = 1, "group" = "生肉"),
		"褪毛禽肉" = list(40, /obj/item/reagent_containers/food/snacks/rogue/meat/poultry, "group_order" = 1, "group" = "生肉"),
		"土豆" = list(10, /obj/item/reagent_containers/food/snacks/grown/potato/rogue, "group_order" = 2, "group" = "蔬菜"),
		"洋葱" = list(10, /obj/item/reagent_containers/food/snacks/grown/onion/rogue, "group_order" = 2, "group" = "蔬菜"),
		"胡萝卜" = list(10, /obj/item/reagent_containers/food/snacks/grown/carrot, "group_order" = 2, "group" = "蔬菜"),
		"芜菁" = list(10, /obj/item/reagent_containers/food/snacks/grown/vegetable/turnip, "group_order" = 2, "group" = "蔬菜"),
		"黄瓜" = list(10, /obj/item/reagent_containers/food/snacks/grown/cucumber, "group_order" = 2, "group" = "蔬菜"),
		"茄子" = list(10, /obj/item/reagent_containers/food/snacks/grown/eggplant, "group_order" = 2, "group" = "蔬菜"),
		"大蒜瓣" = list(10, /obj/item/reagent_containers/food/snacks/grown/garlick/rogue, "group_order" = 2, "group" = "蔬菜"),
		"番茄" = list(10, /obj/item/reagent_containers/food/snacks/grown/fruit/tomato, "group_order" = 2, "group" = "蔬菜"),
		"卷心菜" = list(20, /obj/item/reagent_containers/food/snacks/grown/cabbage/rogue, "group_order" = 2, "group" = "蔬菜"),
		"南瓜" = list(30, /obj/item/natural/shellplant/pumpkin, "group_order" = 2, "group" = "蔬菜"),
		"梨" = list(10, /obj/item/reagent_containers/food/snacks/grown/fruit/pear, "group_order" = 3, "group" = "水果"),
		"柠檬" = list(10, /obj/item/reagent_containers/food/snacks/grown/fruit/lemon, "group_order" = 3, "group" = "水果"),
		"青柠" = list(10, /obj/item/reagent_containers/food/snacks/grown/fruit/lime, "group_order" = 3, "group" = "水果"),
		"橘子" = list(10, /obj/item/reagent_containers/food/snacks/grown/fruit/tangerine, "group_order" = 3, "group" = "水果"),
		"李子" = list(10, /obj/item/reagent_containers/food/snacks/grown/fruit/plum, "group_order" = 3, "group" = "水果"),
		"草莓" = list(10, /obj/item/reagent_containers/food/snacks/grown/fruit/strawberry, "group_order" = 3, "group" = "水果"),
		"黑莓" = list(10, /obj/item/reagent_containers/food/snacks/grown/fruit/blackberry, "group_order" = 3, "group" = "水果"),
		"覆盆子" = list(10, /obj/item/reagent_containers/food/snacks/grown/fruit/raspberry, "group_order" = 3, "group" = "水果"),
		"杰克莓（普通浆果）" = list(10, /obj/item/reagent_containers/food/snacks/grown/berries/rogue, "group_order" = 3, "group" = "水果"),
		"苹果" = list(15, /obj/item/reagent_containers/food/snacks/grown/apple, "group_order" = 3, "group" = "水果"),
		"鸡蛋" = list(8, /obj/item/reagent_containers/food/snacks/egg, "group_order" = 4, "group" = "蛋奶"),
		"牛奶水袋（64u）" = list(50, /obj/item/reagent_containers/glass/bottle/waterskin/milk, "group_order" = 4, "group" = "蛋奶"),
		"鹿肉" = list(30, /obj/item/reagent_containers/food/snacks/rogue/meat/saiga, "group_order" = 1, "group" = "生肉"),
		"鹿肋排" = list(40, /obj/item/reagent_containers/food/snacks/rogue/meat/saiga_ribs, "group_order" = 1, "group" = "生肉"),
		"鹿腰肉" = list(50, /obj/item/reagent_containers/food/snacks/rogue/meat/saiga_loins, "group_order" = 1, "group" = "生肉"),
		"鹿肉上等切块" = list(80, /obj/item/reagent_containers/food/snacks/rogue/meat/saiga_prime, "group_order" = 1, "group" = "生肉"),
	), 1)
