export const NAVIGATOR_CATEGORY_LABELS: Record<string, string> = {
  Weapons: '武器',
  'Light Armor': '轻甲',
  'Heavy Armor': '重甲',
  'Common Garments': '普通衣物',
  'Fine Garments': '华贵衣物',
  Engineering: '工造器具',
  'Crafted Valuables': '工艺珍宝',
  'Looted Valuables': '掠获珍宝',
  'Carved Goods': '雕刻制品',
  'Pottery & Ceramics': '陶器 & 瓷器',
  Trophies: '战利品',
  'Enchantment Scrolls': '附魔卷轴',
  Instruments: '乐器',
  Seafood: '海产',
  'Potions & Reagents': '药剂 & 试剂',
  Miscellaneous: '杂货',
};

export const DANGER_LEVEL_LABELS: Record<string, string> = {
  Safe: '安全',
  Low: '低危',
  Moderate: '中危',
  Dangerous: '危险',
  Bleak: '凶险',
};

export const PUBLIC_MARGIN_LABELS: Record<string, string> = {
  "Gnomes' Margin": '侏儒加价',
  "Porters' Margin": '挑夫加价',
};

export const SHIP_TYPE_LABELS: Record<string, string> = {
  Coaster: '沿岸货船',
  Cog: '柯克帆船',
  Hulk: '霍尔克货船',
  Carrack: '卡拉克帆船',
  Caravel: '卡拉维尔帆船',
  Galleon: '大型远洋帆船',
  'Armada Galleon': '舰队远洋帆船',
  Koch: '抗冰帆船',
  Lodya: '洛迪亚帆船',
  'Aavnic Galley': '阿夫尼克桨帆船',
  'Potentate Hulk': '权贵霍尔克船',
  Sekibune: '关船',
  Bezaisen: '弁才船',
  Shuinsen: '朱印船',
  Atakebune: '安宅船',
  Knarr: '克纳尔货船',
  Ballinger: '巴林格轻帆船',
  'Great Ship': '巨型帆船',
  Longship: '长船',
  'Icebreaker Hulk': '破冰霍尔克船',
  'Great Drakkar': '巨型龙首船',
  Fenrir: '芬里尔',
  Akation: '阿卡提翁轻帆船',
  Dromon: '德罗蒙战船',
  Bireme: '双层桨战船',
  Pamphylos: '潘菲洛斯战船',
  Galley: '桨帆船',
  Nef: '内夫帆船',
  'Great Galley': '大型桨帆船',
  'Chitin Skiff': '甲壳轻舟',
  'Obsidian Galley': '黑曜石桨帆船',
  'Bone Dreadnought': '骸骨无畏舰',
  Dhow: '三角帆船',
  Baghlah: '巴格拉商船',
  'Sand-Galley': '沙海桨帆船',
  'Gilded Carrack': '镀金卡拉克帆船',
};
