#define ITEM_QUALITY_LOOTED      -2
#define ITEM_QUALITY_RUINED      -1
#define ITEM_QUALITY_AWFUL        0
#define ITEM_QUALITY_CRUDE        1
#define ITEM_QUALITY_ROUGH        2
#define ITEM_QUALITY_STANDARD     3
#define ITEM_QUALITY_FINE         4
#define ITEM_QUALITY_FLAWLESS     5
#define ITEM_QUALITY_MASTERWORK   6

#define ITEM_QUALITY_MULT_LOOTED      0.25
#define ITEM_QUALITY_MULT_RUINED      0.20
#define ITEM_QUALITY_MULT_AWFUL       0.35
#define ITEM_QUALITY_MULT_CRUDE       0.65
#define ITEM_QUALITY_MULT_ROUGH       0.85
#define ITEM_QUALITY_MULT_STANDARD    1.00
#define ITEM_QUALITY_MULT_FINE        1.15
#define ITEM_QUALITY_MULT_FLAWLESS    1.30
#define ITEM_QUALITY_MULT_MASTERWORK  1.50

#define ITEM_QUALITY_PREFIX_LOOTED      "捡来的"
#define ITEM_QUALITY_PREFIX_RUINED      "损毁的"
#define ITEM_QUALITY_PREFIX_AWFUL       "糟糕的"
#define ITEM_QUALITY_PREFIX_CRUDE       "粗制的"
#define ITEM_QUALITY_PREFIX_ROUGH       "粗糙的"
#define ITEM_QUALITY_PREFIX_FINE        "精良的"
#define ITEM_QUALITY_PREFIX_FLAWLESS    "无瑕的"
#define ITEM_QUALITY_PREFIX_MASTERWORK  "杰作"

#define ITEM_QUALITY_MULT(Q) ( \
	(Q) == ITEM_QUALITY_LOOTED     ? ITEM_QUALITY_MULT_LOOTED     : ( \
	(Q) == ITEM_QUALITY_RUINED     ? ITEM_QUALITY_MULT_RUINED     : ( \
	(Q) == ITEM_QUALITY_AWFUL      ? ITEM_QUALITY_MULT_AWFUL      : ( \
	(Q) == ITEM_QUALITY_CRUDE      ? ITEM_QUALITY_MULT_CRUDE      : ( \
	(Q) == ITEM_QUALITY_ROUGH      ? ITEM_QUALITY_MULT_ROUGH      : ( \
	(Q) == ITEM_QUALITY_FINE       ? ITEM_QUALITY_MULT_FINE       : ( \
	(Q) == ITEM_QUALITY_FLAWLESS   ? ITEM_QUALITY_MULT_FLAWLESS   : ( \
	(Q) == ITEM_QUALITY_MASTERWORK ? ITEM_QUALITY_MULT_MASTERWORK : \
	ITEM_QUALITY_MULT_STANDARD))))))))
