/proc/get_species_display_name(internal_name)
	var/static/list/display_names = list(
		"Humanb" = "人类（基础）",
		"Humen" = "人类",
		"Elfb" = "精灵（基础）",
		"Elf" = "精灵",
		"Dark Elf" = "黑暗精灵",
		"Half-Elf" = "半精灵",
		"Dwarfb" = "矮人（基础）",
		"Dwarf" = "矮人",
		"Gnome" = "侏儒",
		"Constructb" = "构装体（基础）",
		"Metal Construct" = "金属构装体",
		"Doll" = "瓷偶",
		"Revenant" = "还魂者",
		"Goblin" = "哥布林",
		"Orc" = "兽人",
		"Half Orc" = "半兽人",
		"Aasimar" = "亚斯玛尔",
		"Tiefling" = "提夫林",
		"gnoll" = "豺狼人",
		"verewolf" = "狼人",
		"Ooze" = "软泥",
		"Axian" = "阿克西安",
		"Wild-Kin" = "兽裔",
		"Critterkin" = "小兽裔",
		"Half-Kin" = "半兽裔",
		"Arachnid" = "蛛形族",
		"Drakian" = "龙裔",
		"Harpy" = "哈比",
		"Kobold" = "狗头人",
		"Lamia" = "拉弥亚",
		"Sissean" = "西塞亚",
		"Lupian" = "卢皮安",
		"Fluvian" = "弗卢维安",
		"Tabaxi" = "塔巴西",
		"Venardine" = "维纳丁",
		"volf" = "沃尔夫狼",
		"vernard" = "维纳德狐",
		"spider" = "蜘蛛",
		"saiga" = "赛加羚羊",
		"Lesser Mire Crawler" = "小型沼泽爬行者",
		"cat" = "猫",
		"cabbit" = "猫兔",
		"direbear" = "恐熊",
		"bat" = "蝙蝠",
		"crow" = "乌鸦",
		"None" = "无",
		"Homunculus" = "人造人",
		"Mannequin" = "人形偶",
		"Marionette" = "提线木偶",
		"Puppet" = "傀儡",
		"Cat-Kin" = "猫裔",
		"Dog-Kin" = "犬裔",
		"Volf-Kin" = "狼裔",
		"Lion-Kin" = "狮裔",
		"Venard-Kin" = "狐裔",
		"Tiger-Kin" = "虎裔",
		"Sheep-Kin" = "绵羊裔",
		"Goat-Kin" = "山羊裔",
		"Rous-Kin" = "巨鼠裔",
		"Possum-Kin" = "负鼠裔",
		"Pig-Kin" = "猪裔",
		"Boar-Kin" = "野猪裔",
		"Rabbit-Kin" = "兔裔",
		"Cabbit-Kin" = "猫兔裔",
		"Hare-Kin" = "野兔裔",
		"Horse-Kin" = "马裔",
		"Donkey-Kin" = "驴裔",
		"Hyena-Kin" = "鬣狗裔",
		"Deer-Kin" = "鹿裔",
		"Bear-Kin" = "熊裔",
		"Panda-Kin" = "熊猫裔",
		"Coyote-Kin" = "郊狼裔",
		"Moose-Kin" = "驼鹿裔",
		"Jackal-Kin" = "胡狼裔",
		"Panther-Kin" = "黑豹裔",
		"Lynx-Kin" = "猞猁裔",
		"Leopard-Kin" = "花豹裔",
		"Monkey-Kin" = "猴裔",
		"Bird-Kin" = "鸟裔",
		"Seal-Kin" = "海豹裔",
		"Frog-Kin" = "蛙裔",
		"Bat-Kin" = "蝙蝠裔",
		"Otter-Kin" = "水獭裔",
		"Cow-Kin" = "母牛裔",
		"Bull-Kin" = "公牛裔",
		"Bee-Kin" = "蜂裔",
		"Lizard-Kin" = "蜥蜴裔",
		"Drakian-Kin" = "龙人裔",
		"Dragon-Kin" = "巨龙裔",
		"Insect-Kin" = "虫裔",
		"Spider-Kin" = "蜘蛛裔",
		"Monster-Kin" = "魔物裔",
		"Chimera" = "奇美拉",
		"Moth-Kin" = "蛾裔",
		"Catvolk" = "小猫裔",
		"Dogvolk" = "小犬裔",
		"Volfvolk" = "小狼裔",
		"Lionvolk" = "小狮裔",
		"Venardvolk" = "小狐裔",
		"Tigervolk" = "小虎裔",
		"Sheepvolk" = "小绵羊裔",
		"Goatvolk" = "小山羊裔",
		"Rousvolk" = "小巨鼠裔",
		"Possumvolk" = "小负鼠裔",
		"Pigvolk" = "小猪裔",
		"Boarvolk" = "小野猪裔",
		"Rabbitvolk" = "小兔裔",
		"Cabbitvolk" = "小猫兔裔",
		"Harevolk" = "小野兔裔",
		"Horsevolk" = "小马裔",
		"Donkeyvolk" = "小驴裔",
		"Hyenavolk" = "小鬣狗裔",
		"Deervolk" = "小鹿裔",
		"Bearvolk" = "小熊裔",
		"Pandavolk" = "小熊猫裔",
		"Coyotevolk" = "小郊狼裔",
		"Moosevolk" = "小驼鹿裔",
		"Rakunvolk" = "小浣熊裔",
		"Jackalvolk" = "小胡狼裔",
		"Panthervolk" = "小黑豹裔",
		"Lynxvolk" = "小猞猁裔",
		"Leopardvolk" = "小花豹裔",
		"Monkeyvolk" = "小猴裔",
		"Birdvolk" = "小鸟裔",
		"Sealvolk" = "小海豹裔",
		"Frogvolk" = "小蛙裔",
		"Batvolk" = "小蝙蝠裔",
		"Ottervolk" = "小水獭裔",
		"Cowvolk" = "小母牛裔",
		"Bullvolk" = "小公牛裔",
		"Beevolk" = "小蜂裔",
		"Drakianvolk" = "小龙人裔",
		"Dragonvolk" = "小巨龙裔",
		"Monstervolk" = "小魔物裔",
		"Chimeravolk" = "小奇美拉裔",
		"Half-Cat" = "半猫裔",
		"Half-Dog" = "半犬裔",
		"Half-Volf" = "半狼裔",
		"Half-Lion" = "半狮裔",
		"Half-Venard" = "半狐裔",
		"Half-Tiger" = "半虎裔",
		"Half-Sheep" = "半绵羊裔",
		"Half-Goat" = "半山羊裔",
		"Half-Rous" = "半巨鼠裔",
		"Half-Possum" = "半负鼠裔",
		"Half-Pig" = "半猪裔",
		"Half-Boar" = "半野猪裔",
		"Half-Cabbit" = "半猫兔裔",
		"Half-Rabbit" = "半兔裔",
		"Half-Hare" = "半野兔裔",
		"Half-Horse" = "半马裔",
		"Half-Donkey" = "半驴裔",
		"Half-Hyena" = "半鬣狗裔",
		"Half-Deer" = "半鹿裔",
		"Half-Bear" = "半熊裔",
		"Half-Panda" = "半熊猫裔",
		"Half-Coyote" = "半郊狼裔",
		"Half-Moose" = "半驼鹿裔",
		"Half-Jackal" = "半胡狼裔",
		"Half-Panther" = "半黑豹裔",
		"Half-Lynx" = "半猞猁裔",
		"Half-Leopard" = "半花豹裔",
		"Half-Monkey" = "半猴裔",
		"Half-Bird" = "半鸟裔",
		"Half-Seal" = "半海豹裔",
		"Half-Frog" = "半蛙裔",
		"Half-Bat" = "半蝙蝠裔",
		"Half-Otter" = "半水獭裔",
		"Half-Cow" = "半母牛裔",
		"Half-Bull" = "半公牛裔",
		"Half-Bee" = "半蜂裔",
		"Half-Lizard" = "半蜥蜴裔",
		"Half-Insect" = "半虫裔",
		"Half-Spider" = "半蜘蛛裔",
		"Half-Monster" = "半魔物裔",
		"Half-Drakian" = "半龙裔"
	)
	return display_names[internal_name] || internal_name

/proc/get_species_customization_display_name(internal_name)
	var/static/list/display_names = list(
		"+1 STR" = "+1 力量", "+1 FOR" = "+1 幸运", "+1 INT" = "+1 智力", "+1 CON" = "+1 体质", "+1 WIL" = "+1 意志", "+1 PER" = "+1 感知", "+1 SPD" = "+1 速度",
		"a tangled lineage" = "错综复杂的血统", "bastardized" = "混杂血统", "disputed" = "存疑血统",
		"Abyss" = "深渊", "Abyssal" = "深渊之裔", "Ashen" = "灰烬", "Beach" = "沙滩", "Bone" = "骨白", "Ghost" = "幽魂",
		"Ochre" = "赭色", "Meadow" = "草甸", "Olive" = "橄榄色", "Green" = "绿色", "Moss" = "苔绿", "Taiga" = "针叶林",
		"Bronze" = "青铜", "Red" = "红色", "Frost" = "霜白", "Teal" = "青绿色", "Hadal" = "海渊", "Pale" = "苍白", "Palm" = "棕榈",
		"Brass" = "黄铜", "Iron" = "铁", "Steel" = "钢", "Toper" = "托珀石", "Coal" = "煤", "Cobalt" = "钴", "Granite" = "花岗岩",
		"Jade" = "玉石", "Amythortz" = "紫晶", "Silver" = "银", "Coral" = "珊瑚", "Gold" = "金", "Limestone" = "石灰岩", "Copper" = "铜",
		"Rust" = "铁锈", "Obsidian" = "黑曜石", "Lapis" = "青金石", "Basalt" = "玄武岩", "Platinum" = "铂", "Aurum" = "黄金",
		"Quicksilver" = "水银", "Malachite" = "孔雀石", "Brimstone" = "硫磺", "Ceragyrite" = "角银矿", "Tuscan Red" = "托斯卡纳红", "Smoky Quartz" = "烟水晶",
		"Grenzelhoft" = "格伦泽尔霍夫特", "Hammerhold" = "铁锤堡", "Avar" = "阿瓦尔", "Rockhill" = "岩丘", "Otava" = "奥塔瓦",
		"Etrusca" = "伊特鲁斯卡", "Gronn" = "格隆", "Giza" = "吉萨", "Shalvistine" = "沙尔维斯廷", "Lalvestine" = "拉尔维斯廷",
		"Naledi" = "纳莱迪", "Naledi South" = "南纳莱迪", "Kazengun" = "风郡", "Czwarteki" = "茨瓦尔特基", "Ebon" = "乌木",
		"West Zybantium (Vrdaqnan)" = "西齐班廷（弗尔达克南）", "East Zybantium (Nshkormh)" = "东齐班廷（恩什科尔姆）", "North Zybantium (Chorodiaki)" = "北齐班廷（乔罗迪亚基）",
		"Lalve Steppes" = "拉尔韦草原", "Naledi Coast" = "纳莱迪海岸",
		"Grenzel Woods" = "格伦泽尔林地", "Dandelion Creek" = "蒲公英溪", "Roseveil" = "玫瑰帷幕", "Azuregrove" = "蔚蓝林苑",
		"Arborshome" = "林木家园", "Almondvalle" = "杏仁谷", "Walnut Woods" = "胡桃林地", "Timberborn" = "林木之裔", "Lotus Coast" = "莲花海岸",
		"Etruscan Swamps" = "伊特鲁斯卡沼泽", "Shalvine Forests" = "沙尔文森林", "Lalvestine Thickets" = "拉尔维斯廷灌木林", "Naledi Coverts" = "纳莱迪密林", "Ebon Coverts" = "乌木密林",
		"Commorah" = "科莫拉", "Gloomhaven" = "幽暗港", "Darkpila" = "达克皮拉", "Sshanntynlan" = "斯尚廷兰", "Llurth Dreir" = "卢尔斯·德雷尔",
		"Tafravma" = "塔弗拉夫玛", "Yuethindrynn" = "尤辛德林", "Koredynn" = "科雷丁", "Aiseedrynn" = "艾西德林", "Grenduskra" = "格伦杜斯克拉",
		"Timber-Gronn" = "林木－格隆", "Giza-Vale" = "吉萨－谷地", "Walnut-Stine" = "胡桃－斯廷", "Etrustcan-Dandelion" = "伊特鲁斯卡－蒲公英",
		"Naledi-Born" = "纳莱迪后裔", "Naledi-Southerner" = "纳莱迪南方人", "Kaze-Lotus" = "风郡－莲花", "Grenzel-Vale" = "格伦泽尔－谷地",
		"Etrusca-Lirvas" = "伊特鲁斯卡－利尔瓦斯", "Free Roamers" = "自由漫游者", "Avar Borne" = "阿瓦尔后裔", "Shalvine Roamer" = "沙尔文漫游者",
		"Lalve-Steppes" = "拉尔韦－草原", "Naledi-Otava" = "纳莱迪－奥塔瓦", "Grezel-Avar" = "格伦泽尔－阿瓦尔", "Hammer-Gronn" = "铁锤堡－格隆",
		"Commorah-kin" = "科莫拉裔", "Gloomhaven-kin" = "幽暗港裔", "Darkpila-kin" = "达克皮拉裔", "Sshanntynlan-kin" = "斯尚廷兰裔", "Llurth Dreir-kin" = "卢尔斯·德雷尔裔",
		"Tafravma-kin" = "塔弗拉夫玛裔", "Yuethindrynn-kin" = "尤辛德林裔", "Koredynn-kin" = "科雷丁裔", "Aiseedrynn-kin" = "艾西德林裔", "Grenduskra-kin" = "格伦杜斯克拉裔",
		"Shellcrest" = "甲冠", "Bloodaxe" = "血斧", "Splitjaw" = "裂颚", "Blackhammer" = "黑锤", "Skullseeker" = "寻颅者", "Crescent Fang" = "弦月獠牙",
		"Murkwalker" = "幽沼行者", "Shatterhorn" = "碎角", "Spirit Crusher" = "碎魂者", "Underdweller" = "地底居民", "Underdark" = "幽暗地域",
		"Jehoel" = "耶霍埃尔", "Urvix" = "乌尔维克斯", "Sarvyra" = "萨维拉", "Vheslyn" = "维斯林", "Arlenneth" = "阿伦尼斯", "Nessyss" = "内西斯",
		"Helixia" = "赫利克西亚", "Nymsea" = "宁西亚", "Vodyanev" = "沃迪亚涅夫", "Calvus" = "卡尔乌斯", "Voibion" = "沃伊比翁", "Chyerno" = "切尔诺",
		"Drema" = "德雷玛", "Chir" = "奇尔", "Vesyl" = "维希尔", "Krosec" = "克罗塞克", "Asza" = "阿莎", "Krizzsha" = "克里兹莎",
		"Tosiz" = "托西兹", "Velothel" = "维洛瑟尔", "Ashol" = "阿索尔", "Pyris" = "皮里斯",
		"Archon" = "神使", "Deva" = "天使", "Planetar" = "行星天使", "Solar" = "炽天使", "Empyrea" = "至高天", "Cultor" = "耕耘者",
		"Spiritus" = "圣灵", "Gaeia" = "盖娅", "Celestial" = "天界", "Olympia" = "奥林匹亚", "Necral" = "冥界",
		"Vakran" = "瓦克兰", "Lanarain" = "拉纳莱恩", "Frostfell" = "霜原", "Varghelm" = "瓦格海姆", "Dawnbreak" = "破晓", "Bloodmoon" = "血月",
		"Felsaad" = "费尔萨德", "Hizmut" = "希兹穆特", "Langqan" = "朗钦", "Hun'sek" = "洪塞克",
		"Orange" = "橙色", "Light grey" = "浅灰色", "Dark grey" = "深灰色", "Light orange" = "浅橙色", "Light brown" = "浅棕色", "White brown" = "棕白色", "Dark brown" = "深棕色", "Black" = "黑色",
		"Porcelain" = "瓷白", "Walnut" = "胡桃色", "Sienna" = "赭棕", "Gloom" = "幽暗", "Lotus" = "莲花", "Scarlet" = "猩红", "Scarlet Reach" = "猩红边境",
		"Minotaur" = "牛头人", "Volf" = "沃尔夫狼", "Maneater" = "食人者", "Mud" = "泥土",
		"skin1" = "肤色一", "skin2" = "肤色二", "skin3" = "肤色三",
		"black - cave" = "黑色－洞窟", "black - midnight" = "黑色－午夜", "black - nightsky" = "黑色－夜空", "black - oil" = "黑色－油墨", "black - rogue" = "黑色－游侠",
		"blond - dirty" = "金色－暗金", "blond - drywheat" = "金色－干麦", "blond - pale" = "金色－浅金", "blond - strawberry" = "金色－草莓金", "blonde - moonlight" = "金色－月光",
		"brown - grain" = "棕色－谷物", "brown - mud" = "棕色－泥浆", "brown - oats" = "棕色－燕麦", "brown - soil" = "棕色－土壤", "brown - treebark" = "棕色－树皮",
		"green - grass" = "绿色－青草", "green - leaf" = "绿色－树叶", "green - moss" = "绿色－苔藓", "green - swamp" = "绿色－沼泽",
		"red - autumn" = "红色－秋叶", "red - berry" = "红色－浆果", "red - blood" = "红色－鲜血", "red - flame" = "红色－火焰", "red - sunset" = "红色－夕阳", "red - wine" = "红色－葡萄酒",
		"white - alabaster" = "白色－雪花石", "white - cavedew" = "白色－洞窟露珠", "white - ice" = "白色－寒冰", "white - silver" = "白色－银白", "white - skies" = "白色－天空", "white - snow" = "白色－雪白", "white - spiderweb" = "白色－蛛网", "yellow - sunlight" = "黄色－阳光"
	)
	var/swatch_start = findtext(internal_name, " <span")
	if(swatch_start)
		return "[get_species_customization_display_name(copytext(internal_name, 1, swatch_start))][copytext(internal_name, swatch_start)]"
	return display_names[internal_name] || internal_name

/proc/get_species_display_options(list/options)
	var/list/display_options = list()
	for(var/internal_name in options)
		var/display_name = get_species_customization_display_name(internal_name)
		if(display_name in display_options)
			display_name = "[display_name] ([internal_name])"
		display_options[display_name] = options[internal_name]
	return display_options

/proc/input_species_display_name(mob/user, message, display_title, list/options)
	var/list/display_options = list()
	for(var/internal_name in options)
		var/display_name = get_species_display_name(internal_name)
		if(display_name == internal_name)
			for(var/species_name in GLOB.species_list)
				var/datum/species/species_type = GLOB.species_list[species_name]
				if(initial(species_type.id) == internal_name)
					display_name = get_species_display_name(species_name)
					break
		if(display_name in display_options)
			display_name = "[display_name] ([internal_name])"
		display_options[display_name] = internal_name
	var/choice = input(user, message, display_title) as null|anything in display_options
	return display_options[choice]
